name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      # TODO: add a build step here
      - name: Install dependencies
        run: npm install

      # Not using npm? Change `npm run build` to `yarn build` or `pnpm run build`
      - name: Build qwik
        run: npm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "toursslivers-tt-web"
          entrypoint: "server/entry.deno.js"
          root: "dist"
